/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andres
 */
public class Lendbooks extends javax.swing.JDialog {

    /**
     * Creates new form Lendbooks
     */
    public Lendbooks(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LendBooksActionCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        LBPersonCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        LBBooksCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        LoanDateTF1 = new javax.swing.JTextField();
        LoanDate2 = new javax.swing.JTextField();
        LoanDate3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ReturnDate1 = new javax.swing.JTextField();
        ReturnDate2 = new javax.swing.JTextField();
        ReturnDate3 = new javax.swing.JTextField();
        LendBooksSeeButton = new javax.swing.JButton();
        LendChoiceCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LendBooksExeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LoanIDTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LendBooksActionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insert", "Update", "Delete" }));

        jLabel1.setText("Person");

        jLabel2.setText("Book");

        jLabel3.setText("Loan Date");

        LoanDateTF1.setText("-");

        LoanDate2.setText("-");
        LoanDate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanDate2ActionPerformed(evt);
            }
        });

        LoanDate3.setText("-");

        jLabel4.setText("Return Date");

        ReturnDate1.setText("-");

        ReturnDate2.setText("-");

        ReturnDate3.setText("-");

        LendBooksSeeButton.setText("See");
        LendBooksSeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LendBooksSeeButtonActionPerformed(evt);
            }
        });

        LendChoiceCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Returned", "Not Returned" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LendBooksExeButton.setText("Execute");
        LendBooksExeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LendBooksExeButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Loan ID");

        LoanIDTF.setText("0");

        jButton1.setText("LendBooks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("year");

        jLabel7.setText("month");

        jLabel8.setText("day");

        jLabel9.setText("year");

        jLabel10.setText("month");

        jLabel11.setText("day");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(LendBooksExeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LoanDateTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel7))
                                            .addComponent(LoanDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ReturnDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(ReturnDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LoanDate3)
                                        .addComponent(ReturnDate3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LBPersonCB, 0, 204, Short.MAX_VALUE)
                                    .addComponent(LBBooksCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LoanIDTF))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(68, 68, 68)
                .addComponent(LendBooksActionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LendBooksSeeButton)
                .addGap(136, 136, 136)
                .addComponent(LendChoiceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LendBooksActionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LendBooksSeeButton)
                    .addComponent(LendChoiceCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LoanIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LBPersonCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(LoanDateTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoanDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoanDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LBBooksCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ReturnDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(LendBooksExeButton)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoanDate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanDate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanDate2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> libros;
        ArrayList<String> personas;
        System.out.println(inicio.id_user);
        try {
            libros = connect.connectdbp.UserAvBooksList(inicio.id_user);
            personas = connect.connectdbp.UserKnonwList(inicio.id_user);
            LBBooksCB.removeAllItems();
            LBPersonCB.removeAllItems();
            for (String i: libros) {
                
                LBBooksCB.addItem(i);
            } 
            for (String i: personas) {
                
                LBPersonCB.addItem(i);
            }  
                    
                    } catch (SQLException ex) {
            Logger.getLogger(Lendbooks.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LendBooksExeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LendBooksExeButtonActionPerformed
        // TODO add your handling code here:
        String id_book ="";
        String id_person = "";
        String libro = String.valueOf(LBBooksCB.getSelectedItem());
        String person = String.valueOf(LBPersonCB.getSelectedItem());
 
        
        for(int i=0; i<= libro.length()-1;i++){
            if(libro.substring(i, i+1).equals("-")){
                break;
            }
            else{
               id_book =id_book + libro.substring(i, i+1);
            }
            
        
    }
        for(int i=0; i<= person.length()-1;i++){
            if(person.substring(i, i+1).equals("-")){
                break;
            }
            else{
               id_person =id_person + person.substring(i, i+1);
            }
        }
        System.out.println(id_person);
        System.out.println(id_book);
        
        if(LendBooksActionCB.getSelectedItem().equals("Insert")){
            String loan_date = LoanDateTF1.getText()+"/"+LoanDate2.getText()+"/"+LoanDate3.getText();
            try {
                connectMysql.conexion.InsertPBB(Integer.valueOf(id_person),Integer.valueOf(id_book),loan_date);
            } catch (SQLException ex) {
                Logger.getLogger(Lendbooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        else if (LendBooksActionCB.getSelectedItem().equals("Update")){
            int id_loan = Integer.valueOf(LoanIDTF.getText());
            String loan_date = LoanDateTF1.getText()+"/"+LoanDate2.getText()+"/"+LoanDate3.getText();
            String return_date = ReturnDate1.getText()+"/"+ReturnDate2.getText()+"/"+ReturnDate3.getText();
            System.out.println(loan_date);
            System.out.println(return_date);
            try {
                if(LBBooksCB.getSelectedItem()!=null){
                connectMysql.conexion.UpdatePBBBook(id_loan, Integer.valueOf(id_book));
                }
                connectMysql.conexion.UpdatePBBPerson(id_loan, Integer.valueOf(id_person));
                if(loan_date.equals("-/-/-")){
                    System.out.println(loan_date);
                }
                else {
                    connectMysql.conexion.UpdatePBBLoanD(id_loan, loan_date);
                }
                if(return_date.equals("-/-/-")){
                    connectMysql.conexion.UpdatePBBLoanD(id_loan, return_date);
                }
                else{
                connectMysql.conexion.UpdatePBBReturnD(id_loan, return_date);
            }
            } catch (SQLException ex) {
                Logger.getLogger(Lendbooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        
    }//GEN-LAST:event_LendBooksExeButtonActionPerformed

    private void LendBooksSeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LendBooksSeeButtonActionPerformed
        // TODO add your handling code here:
        if(LendChoiceCB.getSelectedItem().equals("Returned")){
            try {
                jTable1.setModel(connect.connectdbp.showUserReturnedBooks(inicio.id_user));
            } catch (SQLException ex) {
                Logger.getLogger(Lendbooks.class.getName()).log(Level.SEVERE, null, ex);
            }
       
      
                    
                    
    }
        else if(LendChoiceCB.getSelectedItem().equals("Not Returned")){
            try {
                jTable1.setModel(connect.connectdbp.showUserNotReturnedBooks(inicio.id_user));
            } catch (SQLException ex) {
                Logger.getLogger(Lendbooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_LendBooksSeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lendbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lendbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lendbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lendbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Lendbooks dialog = new Lendbooks(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LBBooksCB;
    private javax.swing.JComboBox<String> LBPersonCB;
    private javax.swing.JComboBox<String> LendBooksActionCB;
    private javax.swing.JButton LendBooksExeButton;
    private javax.swing.JButton LendBooksSeeButton;
    private javax.swing.JComboBox<String> LendChoiceCB;
    private javax.swing.JTextField LoanDate2;
    private javax.swing.JTextField LoanDate3;
    private javax.swing.JTextField LoanDateTF1;
    private javax.swing.JTextField LoanIDTF;
    private javax.swing.JTextField ReturnDate1;
    private javax.swing.JTextField ReturnDate2;
    private javax.swing.JTextField ReturnDate3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
