/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;

/**
 *
 * @author andres
 */
public class Stadistics extends javax.swing.JDialog {

    /**
     * Creates new form Stadistics
     */
    public Stadistics(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        Execute = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Books per Genre", "Lended Books", "Lended Books per Genre", "Lended Books per Age" }));

        Execute.setText("Execute");
        Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(Execute)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(Execute)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteActionPerformed
        // TODO add your handling code here:
        
        
        if(jComboBox1.getSelectedItem().equals("Lended Books per Age")){
            
            try {
                JFreeChart chart = ChartFactory.createPieChart3D(
                        "SPlit Second Stats", // chart title
                        connectMysql.conexion.AgePersonsS(), // data
                        true, // include legend
                        true,
                        true);
                
                
                PiePlot3D plot = (PiePlot3D) chart.getPlot();
                plot.setStartAngle(270);    //Rotr gráfica
                plot.setForegroundAlpha(0.60f);     //Transparencia
                plot.setInteriorGap(0.05);
                PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
                    "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
                plot.setLabelGenerator(gen);
                // create chart panel the add it to swing panel in  jframe
                ChartPanel chartPanel = new ChartPanel(chart);
                ChartFrame frame = new ChartFrame("Pie Chart", chart);



                frame.setLocation(1050,490);
                frame.setSize(500,300);

                frame.setVisible(true);
                this.setAlwaysOnTop(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(Stadistics.class.getName()).log(Level.SEVERE, null, ex);
                    }     
        }
        else if(jComboBox1.getSelectedItem().equals("Books per Genre")){
            try {
                JFreeChart chart = ChartFactory.createPieChart3D(
                        "SPlit Second Stats", // chart title
                        connectMysql.conexion.BooksPerGender(), // data
                        true, // include legend
                        true,
                        true);
                
                
                PiePlot3D plot = (PiePlot3D) chart.getPlot();
                plot.setStartAngle(270);    //Rotr gráfica
                plot.setForegroundAlpha(0.60f);     //Transparencia
                plot.setInteriorGap(0.05);
                PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
                    "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
                plot.setLabelGenerator(gen);
                // create chart panel the add it to swing panel in  jframe
                ChartPanel chartPanel = new ChartPanel(chart);
                ChartFrame frame = new ChartFrame("Pie Chart", chart);



                frame.setLocation(1050,490);
                frame.setSize(500,300);

                frame.setVisible(true);
                this.setAlwaysOnTop(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(Stadistics.class.getName()).log(Level.SEVERE, null, ex);
                    }
        }
         
        
        else if(jComboBox1.getSelectedItem().equals("Lended Books per Genre")){
            try {
                JFreeChart chart = ChartFactory.createPieChart3D(
                        "SPlit Second Stats", // chart title
                        connectMysql.conexion.LendedBooksPerGender(), // data
                        true, // include legend
                        true,
                        true);
                
                
                PiePlot3D plot = (PiePlot3D) chart.getPlot();
                plot.setStartAngle(270);    //Rotr gráfica
                plot.setForegroundAlpha(0.60f);     //Transparencia
                plot.setInteriorGap(0.05);
                PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
                    "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
                plot.setLabelGenerator(gen);
                // create chart panel the add it to swing panel in  jframe
                ChartPanel chartPanel = new ChartPanel(chart);
                ChartFrame frame = new ChartFrame("Pie Chart", chart);



                frame.setLocation(1050,490);
                frame.setSize(500,300);

                frame.setVisible(true);
                this.setAlwaysOnTop(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(Stadistics.class.getName()).log(Level.SEVERE, null, ex);
                    }
        }
        
        else if(jComboBox1.getSelectedItem().equals("Lended Books")){
            try {
                JFreeChart chart = ChartFactory.createPieChart3D(
                        "SPlit Second Stats", // chart title
                        connectMysql.conexion.TotalandLended(), // data
                        true, // include legend
                        true,
                        true);
                
                
                PiePlot3D plot = (PiePlot3D) chart.getPlot();
                plot.setStartAngle(270);    //Rotr gráfica
                plot.setForegroundAlpha(0.60f);     //Transparencia
                plot.setInteriorGap(0.05);
                PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
                    "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
                plot.setLabelGenerator(gen);
                // create chart panel the add it to swing panel in  jframe
                ChartPanel chartPanel = new ChartPanel(chart);
                ChartFrame frame = new ChartFrame("Pie Chart", chart);



                frame.setLocation(1050,490);
                frame.setSize(500,300);

                frame.setVisible(true);
                this.setAlwaysOnTop(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(Stadistics.class.getName()).log(Level.SEVERE, null, ex);
                    }
        }
        
        
          // set chart properties
            
    }//GEN-LAST:event_ExecuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stadistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stadistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stadistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stadistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Stadistics dialog = new Stadistics(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Execute;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
